### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by stavanhimal** [saranshsolanki/SketchTranslate#1]
Hi Saransh, 

Thank you for the plugin. It is really great. Just wanted to request a feature that is it possible to add commonly translated languages as a shortcut? Just like you have for Indonesia, Spanish etc? Would love to hear back from you! 

Thank you and a really great job! :D

**Comment by saranshsolanki** [comment]
Hey,
Thank you for reaching out and for the kind words. I'll be pushing a new update to this soon, with lot more functionalities including the one you mentioned. Will update once pushed.
